export const Endpoints = {
    register_user : 'http://localhost/ward_complaint_system_backend/api/register.php',
    login_user : 'http://localhost/ward_complaint_system_backend/api/login.php',
    ciziten_complaint : 'http://localhost/ward_complaint_system_backend/api/complaint.php',
    contact_user: 'http://localhost/ward_complaint_system_backend/api/contact.php',
    get_complaints:'http://localhost/ward_complaint_system_backend/api/get_complaints.php',
    wrad_staff_dashboard:'http://localhost/ward_complaint_system_backend/api/ward_staff_dashboard.php',
    update_complaint_status:'http://localhost/ward_complaint_system_backend/api/ward_staff_update_complaint.php',
    ward_staff_report:'http://localhost/ward_complaint_system_backend/api/ward_staff_report.php',
    user_details:'http://localhost/ward_complaint_system_backend/api/get_users_details.php',
    update_role:'http://localhost/ward_complaint_system_backend/api/update_role.php',
    delete_role:'http://localhost/ward_complaint_system_backend/api/delete_user.php',
    citizen_dashboard:'http://localhost/ward_complaint_system_backend/api/citizen_dashboard.php',
    citizen_dashboard_my_complaints:'http://localhost/ward_complaint_system_backend/api/citizen_my_complaints.php',
}